plugins:
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Naming/MethodParameterName:
  AllowedNames:
    - kw
    - io

Naming/ClassAndModuleCamelCase:
  AllowedNames:
    - V1_2
