module Meibo
  class Course
    attr_reader sourced_id: sourced_id
    attr_reader title: String
    attr_reader org_sourced_id: sourced_id
    attr_reader status: status?
    attr_reader date_last_modified: DateTime?
    attr_reader school_year_sourced_id: sourced_id?
    attr_reader course_code: Array[String]?
    attr_reader grades: Array[grade]
    attr_reader subjects: Array[String]
    attr_reader subject_codes: Array[String]
    attr_reader extension_fields: Hash[Symbol, untyped]

    def initialize: (
      sourced_id: sourced_id,
      title: String,
      org_sourced_id: sourced_id,
      ?status: status?,
      ?date_last_modified: DateTime?,
      ?school_year_sourced_id: sourced_id?,
      ?course_code: Array[String]?,
      ?grades: Array[grade],
      ?subjects: Array[String],
      ?subject_codes: Array[String],
      **Hash[Symbol, untyped] extension_fields
    ) -> void

    def collection: () -> untyped

    def organization: () -> untyped

    def school_year: () -> untyped

    def classes: () -> untyped
  end
end
