module Meibo
  class JapanProfile < ::Meibo::Profile
    type grade = "P1" | "P2" | "P3" | "P4" | "P5" | "P6" | "J1" | "J2" | "J3" | "H1" | "H2" | "H3"

    BUILDERS: Meibo::Profile::builders_type
    DATA_MODELS: Meibo::Profile::data_models_type
    DATA_SET: Meibo::Profile::data_set_type

    def initialize: (
      ?builders: Meibo::Profile::builders_type,
      ?data_models: Meibo::Profile::data_models_type,
      ?data_set: Meibo::Profile::data_set_type
    ) -> void
  end
end
