module Meibo
  class JapanProfile < ::Meibo::Profile
    BUILDERS: { academic_session: untyped, class: untyped, course: untyped, demographic: untyped, enrollment: untyped, org: untyped, role: untyped, user: untyped, user_profile: untyped }

    DATA_MODELS: { file_academic_sessions: untyped, file_classes: untyped, file_courses: untyped, file_demographics: untyped, file_enrollments: untyped, file_orgs: untyped, file_roles: untyped, file_user_profiles: untyped, file_users: untyped }

    DATA_SET: untyped

    def initialize: (?builders: untyped, ?data_models: untyped, ?data_set: untyped) -> void
  end
end
