module Meibo
  class Manifest
    type expected_values = {
      manifest_version: String,
      oneroster_version: String,
      file_academic_sessions: ProcessingMode,
      file_categories: ProcessingMode,
      file_classes: ProcessingMode,
      file_class_resources: ProcessingMode,
      file_courses: ProcessingMode,
      file_course_resources: ProcessingMode,
      file_demographics: ProcessingMode,
      file_enrollments: ProcessingMode,
      file_line_item_learning_objective_ids: ProcessingMode,
      file_line_items: ProcessingMode,
      file_line_item_score_scales: ProcessingMode,
      file_orgs: ProcessingMode,
      file_resources: ProcessingMode,
      file_result_learning_objective_ids: ProcessingMode,
      file_results: ProcessingMode,
      file_result_score_scales: ProcessingMode,
      file_roles: ProcessingMode,
      file_score_scales: ProcessingMode,
      file_user_profiles: ProcessingMode,
      file_user_resources: ProcessingMode,
      file_users: ProcessingMode
    }
    type processing_modes = {
      absent: ProcessingMode,
      bulk: ProcessingMode,
      delta: ProcessingMode
    }
    type attribute_name = :manifest_version | :oneroster_version | :file_academic_sessions | :file_categories | :file_classes | :file_class_resources | :file_courses | :file_course_resources | :file_demographics | :file_enrollments | :file_line_item_learning_objective_ids | :file_line_items | :file_line_item_score_scales | :file_orgs | :file_resources | :file_result_learning_objective_ids | :file_results | :file_result_score_scales | :file_roles | :file_score_scales | :file_user_profiles | :file_user_resources | :file_users | :source_system_name | :source_system_code
    type property_name = "manifest.version" | "oneroster.version" | "file.academicSessions" | "file.categories" | "file.classes" | "file.classResources" | "file.courses" | "file.courseResources" | "file.demographics" | "file.enrollments" | "file.lineItemLearningObjectiveIds" | "file.lineItems" | "file.lineItemScoreScales" | "file.orgs" | "file.resources" | "file.resultLearningObjectiveIds" | "file.results" | "file.resultScoreScales" | "file.roles" | "file.scoreScales" | "file.userProfiles" | "file.userResources" | "file.users" | "source.systemName" | "source.systemCode"
    type attribute_to_property_name_map = Hash[attribute_name, property_name]
    type property_name_to_attribute_map = Hash[property_name, attribute_name]

    MANIFEST_VERSION: "1.0"
    ONEROSTER_VERSION: "1.2"
    PROCESSING_MODES: processing_modes
    PROPERTY_NAME_TO_ATTRIBUTE_MAP: property_name_to_attribute_map
    ATTRIBUTE_TO_PROPERTY_NAME_MAP: attribute_to_property_name_map
    # NOTE: 想定値
    DEFAULT_VALUES: expected_values

    attr_reader manifest_version: "1.0"
    attr_reader oneroster_version: "1.2"
    attr_reader file_academic_sessions: ProcessingMode
    attr_reader file_categories: ProcessingMode
    attr_reader file_classes: ProcessingMode
    attr_reader file_class_resources: ProcessingMode
    attr_reader file_courses: ProcessingMode
    attr_reader file_course_resources: ProcessingMode
    attr_reader file_demographics: ProcessingMode
    attr_reader file_enrollments: ProcessingMode
    attr_reader file_line_item_learning_objective_ids: ProcessingMode
    attr_reader file_line_items: ProcessingMode
    attr_reader file_line_item_score_scales: ProcessingMode
    attr_reader file_orgs: ProcessingMode
    attr_reader file_resources: ProcessingMode
    attr_reader file_result_learning_objective_ids: ProcessingMode
    attr_reader file_results: ProcessingMode
    attr_reader file_result_score_scales: ProcessingMode
    attr_reader file_roles: ProcessingMode
    attr_reader file_score_scales: ProcessingMode
    attr_reader file_user_profiles: ProcessingMode
    attr_reader file_user_resources: ProcessingMode
    attr_reader file_users: ProcessingMode
    attr_reader source_system_name: String?
    attr_reader source_system_code: String?

    def self.build_from_default: (**untyped custom_properties) -> Manifest

    def self.filename: () -> "manifest.csv"

    def self.attribute_to_property_name: (untyped attribute) -> untyped

    def self.filename_for: (untyped attribute) -> ::String

    def self.parse: (untyped csv) -> untyped

    def initialize: (
      manifest_version: "1.0",
      oneroster_version: "1.2",
      file_academic_sessions: ProcessingMode,
      file_categories: ProcessingMode,
      file_classes: ProcessingMode,
      file_class_resources: ProcessingMode,
      file_courses: ProcessingMode,
      file_course_resources: ProcessingMode,
      file_demographics: ProcessingMode,
      file_enrollments: ProcessingMode,
      file_line_item_learning_objective_ids: ProcessingMode,
      file_line_items: ProcessingMode,
      file_line_item_score_scales: ProcessingMode,
      file_orgs: ProcessingMode,
      file_resources: ProcessingMode,
      file_result_learning_objective_ids: ProcessingMode,
      file_results: ProcessingMode,
      file_result_score_scales: ProcessingMode,
      file_roles: ProcessingMode,
      file_score_scales: ProcessingMode,
      file_user_profiles: ProcessingMode,
      file_user_resources: ProcessingMode,
      file_users: ProcessingMode,
      ?source_system_name: String?,
      ?source_system_code: String?
    ) -> void

    def filenames: (processing_mode: untyped) -> untyped

    def file_attributes: (processing_mode: untyped) -> untyped

    def deconstruct: () -> untyped

    def deconstruct_keys: (untyped _keys) -> untyped

    def to_a: () -> untyped

    def to_h: () -> untyped
  end
end
