module Meibo
  type sourced_id = String
  type status = 'active' | 'tobedeleted'

  CSV_ENCODING: "UTF-8"
  ENUM_EXT_PATTERN: Regexp

  attr_accessor self.default_profile: untyped

  def self.current_roster: () -> ::Meibo::Roster?
  def self.with_roster: (::Meibo::Roster roster) { () -> void } -> void

  private

  def self.thread_local_data: () -> untyped
end
