module Meibo
  class JapanProfile < ::Meibo::Profile
    class Enrollment < ::Meibo::Enrollment
      ROLES: { student: "student", teacher: "teacher", administrator: "administrator", guardian: "guardian" }

      # NOTE: 児童生徒の場合primaryはfalse固定
      # MEMO: 保護者の場合もそうでは?
      def initialize: (
        role: Meibo::Enrollment::role_type,
        ?shusseki_no: Integer?,
        ?public_flg: bool?,
        ?primary: bool?,
        sourced_id: sourced_id,
        class_sourced_id: sourced_id,
        school_sourced_id: sourced_id,
        user_sourced_id: sourced_id,
        ?status: status?,
        ?date_last_modified: DateTime?,
        ?begin_date: Date?,
        ?end_date: Date?,
        **Hash[Symbol, untyped] extension_fields
      ) -> void

      def guardian?: () -> untyped
    end
  end
end
